apiVersion: v1
kind: Service
metadata:
  name: nss
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    run: nss
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app: nss
    tier: backend
